apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-monitoring-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.monitoring.svc.cluster.local
    path: "/"
