kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-monitoring-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-monitoring-pv
