apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: kube-state-metrics-http
  namespace: monitoring
  labels:
    app: kube-state-metrics
spec:
  type: ClusterIP
  selector:
    app: kube-state-metrics
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: telemetry
      port: 8081
      protocol: TCP
